global:
  scrape_interval:     5s
  evaluation_interval: 5s

  external_labels:
      monitor: 'prometheus-grafana-exporter'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: node
    static_configs:
    - targets: ['host.docker.internal:9100']
