apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000

  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090

  - name: Vision Control
    type: simpod-json-datasource
    access: proxy
    url: http://middleware:8000/api
